function obsubset = importfileM(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  OBSUBSET = IMPORTFILE(FILE) reads data from the first worksheet in
%  the Microsoft Excel spreadsheet file named FILE.  Returns the numeric
%  data.
%
%  OBSUBSET = IMPORTFILE(FILE, SHEET) reads from the specified worksheet.
%
%  OBSUBSET = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  obsubset = importfile("C:\Users\master\Documents\MATLAB\ZMQ_03\obsubset.xlsx", "obsubset", [2, 7479]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-May-2020 00:38:52

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 7479];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 23);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "B" + dataLines(1, 1) + ":X" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Bid", "B0", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "Ask", "A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "y"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ImportErrorRule = "omitrow";
opts.MissingRule = "omitrow";

% Specify variable properties
opts = setvaropts(opts, ["Bid", "B0", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "Ask", "A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "y"], "TreatAsMissing", '');

% Import the data
obsubset = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "B" + dataLines(idx, 1) + ":X" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    obsubset = [obsubset; tb]; %#ok<AGROW>
end

%% Convert to output type
obsubset = table2array(obsubset);
end